name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Visual Studio Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: |
        cl.exe /EHsc /std:c++17 MouseRed.cpp /link user32.lib

    - name: List Build Output
      run: dir *.exe